#!/bin/sh
export GR_DONT_LOAD_PREFS=1
export srcdir=/home/agrim/Desktop/340_PROJECT/gr-FHSS/lib
export PATH=/home/agrim/Desktop/340_PROJECT/gr-FHSS/lib/lib:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH
test-FHSS 
